export const SET_CART_MENU = "SET_CART_MENU";

export const FETCH_OFFERS_PENDING = "FETCH_OFFERS_PENDING";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_FAILURE = "FETCH_OFFERS_FAILURE";

export const FETCH_RESTAURANTSLIST = "FETCH_RESTAURANTSLIST";
export const RESTAURANTSLIST_RECEIVED = "RESTAURANTSLIST_RECEIVED";
